import Waiting from "olive/components/waiting";
import Url from "olive/components/url";
import ResponseProcessor from "olive/mvc/responseProcessor";
import LiteEvent from "olive/components/liteEvent";
export default class AjaxRedirect implements IService {
    protected url: Url;
    private responseProcessor;
    private waiting;
    private requestCounter;
    private targetKeySeed;
    private inFlight;
    ajaxChangedUrl: number;
    isAjaxRedirecting: boolean;
    beforeRedirect: LiteEvent<IEventArgs>;
    constructor(url: Url, responseProcessor: ResponseProcessor, waiting: Waiting);
    enableRedirect(selector: JQuery): void;
    protected onRedirected(trigger: JQuery, title: string, url: string): void;
    protected onMainTagRedirected(trigger: JQuery, title: string, url: string): boolean;
    protected isInternalMainTag(mainTag: JQuery): boolean;
    protected finalTargetAsMainTag(trigger: JQuery): JQuery | undefined;
    private targetKeyFor;
    private targetStillPresent;
    private isCurrent;
    private abortPending;
    private abortContainedBy;
    cancelPending(trigger?: JQuery): void;
    protected onRedirectionFailed(trigger: JQuery, url: string, response: JQueryXHR): void;
    private redirect;
    go(inputUrl: string, trigger?: JQuery, isBack?: boolean, keepScroll?: boolean, addToHistory?: boolean, onComplete?: (successful: boolean) => void, ajaxTarget?: string, ajaxhref?: string): boolean;
    private uuidv4;
}
