const Services = {
    Alert: "alert",
    CrossDomainEvent: "crossDomainEvent",
    Form: "form",
    Grid: "grid",
    Grouping: "grouping",
    GroupingFactory: "groupingFactory",
    LiteEvent: "liteEvent",
    MasterDetail: "masterDetail",
    Modal: "modal",
    Paging: "paging",
    Sorting: "sorting",
    Url: "url",
    Validate: "validate",
    Waiting: "waiting",
    AjaxRedirect: "ajaxRedirect",
    FormAction: "formAction",
    StandardAction: "standardAction",
    AutoComplete: "autoComplete",
    AutoCompleteFactory: "autoCompleteFactory",
    CkEditorFileManager: "ckEditorFileManager",
    CKEditorFileManagerFactory: "ckEditorFileManagerFactory",
    ConfirmBox: "confirmBox",
    CustomCheckbox: "customCheckbox",
    CustomRadio: "customRadio",
    DateDropdown: "dateDropdown",
    DatePicker: "datePicker",
    DateTimePicker: "dateTimePicker",
    DateTimePickerBase: "dateTimePickerBase",
    FileUpload: "fileUpload",
    FileUploadFactory: "fileUploadFactory",
    GlobalSearch: "globalSearch",
    HtmlEditor: "htmlEditor",
    InstantSearch: "instantSearch",
    MultiSelect: "multiSelect",
    NumericUpDown: "numericUpDown",
    PasswordStength: "passwordStength",
    SanityAdapter: "sanityAdapter",
    Select: "select",
    Slider: "slider",
    SliderFactory: "sliderFactory",
    SubMenu: "subMenu",
    TimeControl: "timeControl",
    UserHelp: "userHelp",
};

export default Services;