export default class OlivePage {
    modal: any;
    constructor();
    _initializeActions: any[];
    onInit(action: any): void;
    _preInitializeActions: any[];
    onPreInit(action: any): void;
    pageLoad(container?: JQuery, trigger?: any): void;
    initializeUpdatedPage(container?: JQuery, trigger?: any): void;
    initialize(): void;
    skipNewWindows(): void;
    enableDragSort(container: any): void;
    enablePasswordStengthMeter(container: any): void;
    enableDateDropdown(input: any): void;
    openLinkModal(event: JQueryEventObject): boolean;
    toJson(data: any): any;
    runStartupActions(container?: JQuery, trigger?: any, stage?: string): void;
    canAutoFocus(input: JQuery): boolean;
    awaitingAutocompleteResponses: number;
    returnToPreviousPage(target: any): boolean;
    cleanGetFormSubmit(event: JQueryEventObject): boolean;
    executeActions(actions: any, trigger?: any): void;
    executeAction(action: any, trigger: any): boolean;
    closeCurrentModal(refreshParrent?: boolean): any;
    openModal(event: any, url?: any, options?: any): void;
    executeNotifyAction(action: any, trigger: any): void;
    executeRedirectAction(action: any, trigger: any): void;
    openWindow(url: string, target: string): void;
    refresh(keepScroll?: boolean): void;
    dynamicallyLoadedScriptFiles: any[];
    replaceMain(element: JQuery, trigger: any): void;
    invokeAjaxActionResult(response: any, containerModule: any, trigger: any): void;
    enableUserHelp(element: JQuery): void;
}
