name: Publish Olive MvcJs Package

on:
  push:
    branches: [ Add-Publish-Action ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - run: npm install typescript@4.2.3 -g
    
    - run: tsc --project bundle-tsconfig.json

    - run: node ./bundling-helper/fix-bundle-modules