name: Publish Olive MvcJs Package

on:
  push:
    branches: [ Add-Publish-Action ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - run: yarn install --frozen-lockfile
    
    - run: yarn pack --filename=release.tgz

    - uses: Klemensas/action-autotag@stable
      id: update_tag
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        tag_prefix: "v"