name: Publish Olive MvcJs Package

on:
  push:
    branches: [ Add-Github-Action ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - run: npm install typescript@4.2.3 -g
    
    - run: tsc --project bundle-tsconfig.json

    - run: node ./bundling-helper/fix-bundle-modules

    - uses: Klemensas/action-autotag@stable
      id: update_tag
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Create Release
      if: steps.update_tag.outputs.tagname
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.update_tag.outputs.tagname }}
        release_name: ${{ steps.update_tag.outputs.tagname }}