name: Publish Olive MvcJs Package (excyte)

on:
  push:
    branches: [ excyte ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'

    - run: yarn install --frozen-lockfile

    - run: yarn build

    - run: yarn build:bundle

    - run: yarn pack

    - uses: Klemensas/action-autotag@stable
      id: update_tag
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Create Release
      if: steps.update_tag.outputs.tagname
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.update_tag.outputs.tagname }}
        name: ${{ steps.update_tag.outputs.tagname }}
        files: package.tgz
